apiVersion: v1
kind: Secret
metadata:
  name: habit-tracker-secrets
  namespace: habit-tracker
type: Opaque
stringData:
  CORE_DB_PASSWORD: "postgres"
  USERS_DB_PASSWORD: "postgres"
  NOTIFICATION_DB_PASSWORD: "postgres"
  WORKFLOW_DB_PASSWORD: "postgres"
  RABBITMQ_PASSWORD: "guest"
